### ISSUE TITLE
DPM8650 same code?

### ISSUE THREAD

**Issue by STE2k** [Lotiq/DPM_8600#1]
I received a new DPM8650 TTL - Version. Should work also I guess? With your code I get readings of 0 at every value.

**Comment by Lotiq** [comment]
Hi Stefan, 

Sorry, have missed your messages earlier. It has been way too long since I worked on the library, hardly remember how I built it 😅. Hopefully, you found a way to resolve your issue.

Good luck with your project!

Best,
Timothy
